package com.qtshe.cpt.mapper;

import com.qtshe.cpt.model.Country;
import java.util.List;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int updateByPrimaryKey(Country record);
}