package com.qtshe.cpt.mapper;

import com.qtshe.cpt.model.Userprofile;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserprofileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int deleteByPrimaryKey(@Param("id") Long id, @Param("userid") String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int insert(Userprofile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    Userprofile selectByPrimaryKey(@Param("id") Long id, @Param("userid") String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    List<Userprofile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int updateByPrimaryKey(Userprofile record);
}