package com.qtshe.cpt.mapper;

import com.qtshe.cpt.model.UserData;
import java.util.List;

public interface UserDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int insert(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    UserData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    List<UserData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserData record);
}