package com.qtshe.cpt.mapper;

import com.qtshe.cpt.model.UserLoginInfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int insert(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    UserLoginInfo selectByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    List<UserLoginInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserLoginInfo record);
}