package com.qtshe.cpt.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: country
 */
@Data
public class Country implements Serializable {
    /**
     * 主键
     *
     * Table:     country
     * Column:    Id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 名称
     *
     * Table:     country
     * Column:    countryname
     * Nullable:  true
     */
    private String countryname;

    /**
     * 代码
     *
     * Table:     country
     * Column:    countrycode
     * Nullable:  true
     */
    private String countrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table country
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}