package com.qtshe.cpt.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: t_users
 */
@Data
public class TUsers implements Serializable {
    /**
     * Table:     t_users
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * Table:     t_users
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * Table:     t_users
     * Column:    sex
     * Nullable:  true
     */
    private String sex;

    /**
     * Table:     t_users
     * Column:    age
     * Nullable:  true
     */
    private Integer age;

    /**
     * Table:     t_users
     * Column:    phone
     * Nullable:  true
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_users
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}