package com.qtshe.cpt.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: userprofile
 */
@Data
public class Userprofile implements Serializable {
    /**
     * id
     *
     * Table:     userprofile
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 用户ID UUID
     *
     * Table:     userprofile
     * Column:    UserID
     * Nullable:  false
     */
    private String userid;

    /**
     * 登录用户名
     *
     * Table:     userprofile
     * Column:    login_name
     * Nullable:  true
     */
    private String loginName;

    /**
     * 用户号码
     *
     * Table:     userprofile
     * Column:    PhoneNum
     * Nullable:  true
     */
    private String phonenum;

    /**
     * 用户邮箱
     *
     * Table:     userprofile
     * Column:    email
     * Nullable:  true
     */
    private String email;

    /**
     * 密码
     *
     * Table:     userprofile
     * Column:    Password
     * Nullable:  false
     */
    private String password;

    /**
     * 用户状态
            1 正常
            2 锁定
     *
     * Table:     userprofile
     * Column:    Status
     * Nullable:  false
     */
    private String status;

    /**
     * 注册平台
     *
     * Table:     userprofile
     * Column:    platform
     * Nullable:  true
     */
    private Integer platform;

    /**
     * 创建时间
     *
     * Table:     userprofile
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 创建人
     *
     * Table:     userprofile
     * Column:    create_by
     * Nullable:  true
     */
    private String createBy;

    /**
     * 修改时间
     *
     * Table:     userprofile
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;

    /**
     * 修改人
     *
     * Table:     userprofile
     * Column:    update_by
     * Nullable:  true
     */
    private Date updateBy;

    /**
     * 数据状态 0：正常  1 删除 
     *
     * Table:     userprofile
     * Column:    data_status
     * Nullable:  true
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userprofile
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}