package com.qtshe.cpt.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: user login info
 */
@Data
public class UserLoginInfo implements Serializable {
    /**
     * Table:     user login info
     * Column:    Id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 登录名
     *
     * Table:     user login info
     * Column:    username
     * Nullable:  false
     */
    private String username;

    /**
     * 登录时间
     *
     * Table:     user login info
     * Column:    logindate
     * Nullable:  true
     */
    private Date logindate;

    /**
     * 登录IP
     *
     * Table:     user login info
     * Column:    loginip
     * Nullable:  true
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user login info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}