package com.qtshe.cpt.model;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: user_info
 */
@Data
public class UserInfo implements Serializable {
    /**
     * Table:     user_info
     * Column:    Id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 用户名
     *
     * Table:     user_info
     * Column:    username
     * Nullable:  false
     */
    private String username;

    /**
     * 密码
     *
     * Table:     user_info
     * Column:    password
     * Nullable:  true
     */
    private String password;

    /**
     * 用户类型
     *
     * Table:     user_info
     * Column:    usertype
     * Nullable:  true
     */
    private String usertype;

    /**
     * 是否可用
     *
     * Table:     user_info
     * Column:    enabled
     * Nullable:  true
     */
    private Integer enabled;

    /**
     * 真实姓名
     *
     * Table:     user_info
     * Column:    realname
     * Nullable:  true
     */
    private String realname;

    /**
     * QQ
     *
     * Table:     user_info
     * Column:    qq
     * Nullable:  true
     */
    private String qq;

    /**
     * Table:     user_info
     * Column:    email
     * Nullable:  true
     */
    private String email;

    /**
     * 联系电话
     *
     * Table:     user_info
     * Column:    tel
     * Nullable:  true
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}