package com.qtshe.cpt.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: user_data
 */
@Data
public class UserData implements Serializable {
    /**
     * id
     *
     * Table:     user_data
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 用户id
     *
     * Table:     user_data
     * Column:    user_id
     * Nullable:  true
     */
    private String userId;

    /**
     * 用户昵称
     *
     * Table:     user_data
     * Column:    nick_name
     * Nullable:  true
     */
    private String nickName;

    /**
     * 用户真实姓名
     *
     * Table:     user_data
     * Column:    real_name
     * Nullable:  true
     */
    private String realName;

    /**
     * 用户生日
     *
     * Table:     user_data
     * Column:    birthday
     * Nullable:  true
     */
    private String birthday;

    /**
     * 用户身份证号
     *
     * Table:     user_data
     * Column:    id_card
     * Nullable:  true
     */
    private String idCard;

    /**
     * 身份证号是否验证 0 未验证 1已验证
     *
     * Table:     user_data
     * Column:    id_card_flag
     * Nullable:  true
     */
    private Integer idCardFlag;

    /**
     * 地址
     *
     * Table:     user_data
     * Column:    address
     * Nullable:  true
     */
    private String address;

    /**
     * 创建时间
     *
     * Table:     user_data
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 创建人
     *
     * Table:     user_data
     * Column:    create_by
     * Nullable:  true
     */
    private String createBy;

    /**
     * 修改时间
     *
     * Table:     user_data
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;

    /**
     * 修改人
     *
     * Table:     user_data
     * Column:    update_by
     * Nullable:  true
     */
    private Date updateBy;

    /**
     * 数据状态 0：正常  1 删除 
     *
     * Table:     user_data
     * Column:    data_status
     * Nullable:  true
     */
    private Integer dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_data
     *
     * @mbggenerated Tue Nov 27 11:26:30 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;
}